apiVersion: v1
kind: Namespace
metadata:
  name: {TENANT_ID}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {TENANT_ID}-premium
  namespace: flux-system
spec:
  releaseName: {TENANT_ID}-premium
  targetNamespace: {TENANT_ID}
  storageNamespace: {TENANT_ID}
  interval: 1m0s
  chart:
    spec:
      chart: ./helm-charts/helm-tenant-chart
      version: "{RELEASE_VERSION}.x"
      sourceRef:
        kind: GitRepository
        name: helm-tenant-chart
  values:
    tenantId: {TENANT_ID}
    apps: {}
