apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mariadb
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: MYSQL_USER  # Updated to match the key in your secret
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: MYSQL_PASSWORD  # Updated to match the key in your secret
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: MYSQL_DATABASE  # Added to specify the database name
  