apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: {{ include "wordpress-mysql.fullname" . }}-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}   # Ensures size is referenced from values.yaml
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}   # Ensure storage class is set correctly
