{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.enabled (and $appConfig.autoscaling (hasKey $appConfig.autoscaling "enabled") $appConfig.autoscaling.enabled) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.tenantId }}-{{ $appName }}-hpa
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}-{{ $appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.tenantId }}-{{ $appName }}
  minReplicas: {{ $appConfig.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $appConfig.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if $appConfig.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $appConfig.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $appConfig.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $appConfig.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
