{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.enabled $appConfig.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Values.tenantId }}-ingress-{{ $appName }}"
  namespace: {{ $.Values.tenantId }}
  labels:
    app.kubernetes.io/name: "{{ $.Chart.Name }}-{{ $appName }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    {{- if eq $appConfig.ingress.className "alb" }}
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/group.name: "tenants-lb"
    {{- end }}
    {{- with $appConfig.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $appConfig.ingress.className | quote | default "nginx" }}
  rules:
  - http:
      paths:
      - path: /
        pathType: {{ $appConfig.ingress.pathType | default "ImplementationSpecific" }}
        backend:
          service:
            name: "{{ $.Values.tenantId }}-{{ $appName }}"
            port:
              number: {{ (and (hasKey $appConfig "service") (hasKey $appConfig.service "port")) | ternary ($appConfig.service.port | default 80) 80 }}
{{- end }}
{{- end }}
