apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ $appName }}-pvc # Ensure unique name per app
  namespace: {{ $.Values.tenantId }}
spec:
  storageClassName: {{ $.Values.storageClassName | default "linode-block-storage-retain" }} # Correct default value
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $appConfig.storageSize | default "1Gi" }} # Use app-specific storageSize or default
