apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ $.Values.tenantId }}
spec:
  storageClassName: {{ $.Values.storageClassName | default "linode-block-storage-retain" }} # Correct default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.apps.wordpress.storageSize | default "1Gi" }} # Ensure app-specific default
