apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ $.Values.tenantId }}
spec:
  storageClassName: {{ $.Values.storageClassName | default "linode-block-storage-retain" }} # Use default if not provided
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.apps.wordpress.storageSize | default "1Gi" }} # Provide a default if storageSize is missing
