{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.enabled (hasKey $appConfig "service") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $appName }}
  namespace: {{ $.Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }} # Default to ClusterIP if not set
  ports:
    - port: {{ $appConfig.service.port | default 80 }} # Default to port 80 if not set
      targetPort: http
      protocol: TCP
  selector:
    app: {{ $.Release.Name }}-{{ $appName }}
{{- end }}
{{- else }}
# If service is not defined or enabled, skip creating a Service resource for this app
{{- end }}
