{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.enabled (hasKey $appConfig "service") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.tenantId }}-{{ $appName }}
  namespace: {{ $.Values.tenantId | default "default" }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }}  # Will dynamically use LoadBalancer or ClusterIP
  ports:
    - port: {{ $appConfig.service.port | default 80 }}
      targetPort: {{ $appConfig.service.targetPort | default $appConfig.service.port | default 80 }}
      protocol: TCP
  selector:
    app: {{ $.Values.tenantId }}-{{ $appName }}
{{- end }}
{{- end }}
