apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }} # Default to ClusterIP if not set
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-wordpress