{{- if and (hasKey .Values.apps "mysql") .Values.apps.mysql.enabled .Values.apps.mysql.useStatefulSet }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.tenantId }}-mysql
  namespace: {{ $.Values.tenantId }}
  labels:
    app.kubernetes.io/name: "{{ $.Chart.Name }}-mysql"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
    app: {{ $.Values.tenantId }}-mysql
spec:
  replicas: {{ $.Values.apps.mysql.replicaCount }}
  serviceName: {{ $.Values.tenantId }}-mysql
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ $.Chart.Name }}-mysql"
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      app: {{ $.Values.tenantId }}-mysql
  template:
    metadata:
      annotations:
        {{- toYaml $.Values.apps.mysql.podAnnotations | nindent 8 }}
      labels:
        app.kubernetes.io/name: "{{ $.Chart.Name }}-mysql"
        app.kubernetes.io/instance: "{{ $.Release.Name }}"
        app: {{ $.Values.tenantId }}-mysql
    spec:
      {{- if $.Values.apps.mysql.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.apps.mysql.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if and $.Values.apps.mysql.serviceAccount (hasKey $.Values.apps.mysql.serviceAccount "create") $.Values.apps.mysql.serviceAccount.create }}{{ $.Values.tenantId }}-mysql{{ else }}default{{ end }}
      securityContext:
        {{- toYaml $.Values.apps.mysql.podSecurityContext | nindent 8 }}
      containers:
        - name: mysql
          securityContext:
            {{- toYaml $.Values.apps.mysql.securityContext | nindent 12 }}
          image: "{{ $.Values.apps.mysql.image.repository }}:{{ $.Values.apps.mysql.image.tag }}"
          imagePullPolicy: {{ $.Values.apps.mysql.image.pullPolicy }}
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml $.Values.apps.mysql.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml $.Values.global.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml $.Values.apps.mysql.affinity | nindent 8 }}
      tolerations:
        {{- toYaml $.Values.global.tolerations | nindent 8 }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ $.Values.apps.mysql.storageClassName | default "linode-block-storage-retain" }} # Ensure configurability
        resources:
          requests:
            storage: 5Gi
{{- end }}
