{{- if and (hasKey .Values.apps "mysql") .Values.apps.mysql.enabled .Values.apps.mysql.useStatefulSet }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.tenantId }}-mysql
  namespace: {{ $.Values.tenantId }}
  labels:
    app.kubernetes.io/name: "{{ $.Chart.Name }}-mysql"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
    app: {{ $.Values.tenantId }}-mysql
spec:
  replicas: {{ $.Values.apps.mysql.replicaCount }}
