apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operate-workflow-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
