additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--entrypoints.websecure.http.tls=true"
  - "--certificatesresolvers.default.acme.tlschallenge=true"
  - "--certificatesresolvers.default.acme.email=harshexample.com"
  - "--certificatesresolvers.default.acme.storage=/data/acme.json"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data  # Persistent storage for certificates

podSecurityContext:
  fsGroup: 65532
  runAsUser: 65532
  runAsGroup: 65532