apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operate-workflow-clusterrole
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["pods", "pods/log", "deployments", "jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operate-workflow-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: operate-workflow-clusterrole
  apiGroup: rbac.authorization.k8s.io
