apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: traefik
data:
  rclone.conf: |
    [linode]
    type = s3
    provider = Linode
    endpoint = us-ord-1.linodeobjects.com
    access_key_id = {access_key}
      secret_access_key = {secret_access_key}
