apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: traefik
data:
  rclone.conf: |
    [linode]
    type = s3
    provider = Linode
    access_key_id = G7PSEO5AH8MRL6ZB8NJX 
    secret_access_key = we9fw4aMMPM6PBoiOH9eKgEaHPKBZCJObCo7lhre
    endpoint = us-ord-1.linodeobjects.com
