apiVersion: v1
kind: ServiceAccount
metadata:
  name: operate-workflow-sa
  namespace: argo-workflows
imagePullSecrets:
  - name: dockerhub-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-workflows
  name: operate-workflow-role
rules:
- apiGroups: ["", "apps", "batch", "argoproj.io"]
  resources: ["pods", "pods/log", "workflows", "jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-rolebinding
  namespace: argo-workflows
subjects:
- kind: ServiceAccount
  name: operate-workflow-sa
  namespace: argo-workflows
roleRef:
  kind: Role
  name: operate-workflow-role
  apiGroup: rbac.authorization.k8s.io
