apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-acme-json
  namespace: traefik
spec:
  schedule: "*/30 * * * *"  # Sync every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone
            image: rclone/rclone:latest
            envFrom:
              - secretRef:
                  name: linode-object-storage-config
            volumeMounts:
            - name: traefik-data
              mountPath: /data
            - name: rclone-config
              mountPath: /config
              subPath: rclone.conf
            command:
              - /bin/sh
              - -c
              - |
                rclone copy /data/acme.json linode:armored-host --config /config/rclone.conf
          volumes:
          - name: traefik-data
            persistentVolumeClaim:
              claimName: traefik
          - name: rclone-config
            configMap:
              name: rclone-config
          restartPolicy: OnFailure
