apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync
  namespace: traefik
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rclone
              image: rclone/rclone:latest
              args:
                - sync
                - /data
                - linode:armored-host  # Replace with your bucket name
                - --config=/config/rclone.conf
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: linode-s3-credentials
                      key: access_key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: linode-s3-credentials
                      key: secret_key
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: rclone-config
                  mountPath: /config/rclone.conf
                  subPath: rclone.conf
          restartPolicy: OnFailure
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: traefik
            - name: rclone-config
              configMap:
                name: rclone-config
