apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: tenant-onboarding-sensor
  namespace: argo-events
spec:
  dependencies:
  - name: onboarding-event-dep
    eventSourceName: amqp
    eventName: example
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
  - template:
      name: tenant-onboarding-trigger
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dependencyName: onboarding-event-dep
            dataKey: body.tenant_id
        - dest: spec.arguments.parameters.1.value
          src:
            dependencyName: onboarding-event-dep
            dataKey: body.tenant_tier
        - dest: spec.arguments.parameters.2.value
          src:
            dependencyName: onboarding-event-dep
            dataKey: body.release_version
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: tenant-onboarding-
              namespace: argo-workflows
            spec:
              entrypoint: tenant-provisioning
              arguments:
                parameters:
                - name: tenant_id
                  value: ""
                - name: tenant_tier
                  value: ""
                - name: release_version
                  value: ""
              templates:
              - name: tenant-provisioning
                steps:
                - - name: validate-if-tenant-exists
                    templateRef:
                      name: tenant-onboarding-template
                      template: validate-if-tenant-exists
                - - name: create-tenant-helm-release
                    templateRef:
                      name: tenant-onboarding-template
                      template: create-tenant-helm-release
