additionalArguments:
  - "--entrypoints.web.address=:8081"                      # Use non-privileged port for HTTP
  - "--entrypoints.websecure.address=:8443"                # Use non-privileged port for HTTPS
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--entrypoints.websecure.http.tls=true"
  - "--certificatesresolvers.letsencrypt.acme.email=faralpha615@gmail.com"  # Replace with your email
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"       # Location for ACME storage
  - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"

persistence:
  enabled: true                                           # Enable persistence
  accessMode: ReadWriteOnce
  size: 1Gi                                               # Persistent volume size
  path: /data                                             # Path to store ACME file

podSecurityContext:
  fsGroup: 65532                                          # Group ID for Traefik process
  runAsUser: 65532                                        # Run Traefik as non-root user
  runAsGroup: 65532                                       # Group ID for Traefik user

initContainers:
  - name: fix-permissions
    image: busybox
    command: ["sh", "-c", "touch /data/acme.json && chmod 600 /data/acme.json"]
    volumeMounts:
      - name: data
        mountPath: /data

service:
  type: LoadBalancer                                      # Expose service as LoadBalancer
  ports:
    - name: web
      port: 80                                            # Map external HTTP traffic to port 8081
      targetPort: 8081
    - name: websecure
      port: 443                                           # Map external HTTPS traffic to port 8443
      targetPort: 8443
