apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: wordpress-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/devnouiq/linode
  ref:
    branch: main
  ignore: |
    *.md     # Ignore markdown files
  paths:
    - ./charts
    - ./clusters/my-cluster
    - ./tenant
