apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-tenant-chart
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/devnouiq/linode.git
  ref:
    branch: main
  ignore: |
    *.md
    .gitignore
    README.md
