apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default                # Adjust the namespace as needed
spec:
  releaseName: wordpress             # Name of the release in Helm
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami                # Assuming you use the Bitnami chart for WordPress
      version: 15.2.24               # Specify the version of the chart
  interval: 1m                       # Flux will check for updates every 1 minute
  values:
    image:
      repository: wordpress
      tag: latest
    wordpressUsername: admin
    wordpressPassword: password
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"
    mariadb:
      enabled: true
      db:
        user: wordpress
        password: wordpress-password
        name: wordpress
    service:
      type: ClusterIP
      port: 80
    mysql:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: standard
