apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default  # Adjust this if deploying to a different namespace
spec:
  interval: 1m  # Flux will check for updates every 1 minute
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: 15.2.24  # Specify the version of the chart you want
      sourceRef:
        kind: HelmRepository
        name: bitnami  # This references the HelmRepository resource created above
        namespace: flux-system  # Adjust if the HelmRepository is in a different namespace
  values:
    image:
      repository: wordpress
      tag: latest
    wordpressUsername: admin
    wordpressPassword: password
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"
    mariadb:
      enabled: true
      db:
        user: wordpress
        password: wordpress-password
        name: wordpress
    service:
      type: ClusterIP
      port: 80
    mysql:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: standard
