apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 1m
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: 15.2.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: wordpress
      tag: latest
    wordpressUsername: admin
    wordpressPassword: password
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"
    mariadb:
      enabled: true
      db:
        user: wordpress
        password: wordpress-password
        name: wordpress
      auth:
        rootPassword: "$MARIADB_ROOT_PASSWORD" 
    service:
      type: ClusterIP
      port: 80
    mysql:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: standard
