# Default values for tenant-chart.
tenantId: "example-tenant"
host: "example-tenant.givemeipdomain.duckdns.org"

# Global settings for node selection and tolerations
global:
  storageClassName: linode-block-storage-retain
  namespace: default

# Application configurations
apps:
  wordpress:
    enabled: true
    replicaCount: 1
    image:
      repository: "wordpress"
      tag: "latest"
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 80
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      pathType: Prefix
      tls: []
    affinity: {}
    storageClassName: linode-block-storage-retain
    storageSize: "1Gi"

  mysql:
    enabled: true
    useStatefulSet: true
    replicaCount: 1
    image:
      repository: "mysql"
      tag: "8.0"
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 3306
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    ingress:
      enabled: false
    affinity: {}
    storageClassName: linode-block-storage-retain
    storageSize: "5Gi"

  producer:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    image:
      repository: "nginx"
      tag: "latest"
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 64Mi
        cpu: 50m

  consumer:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 9090
    ingress:
      enabled: false
    image:
      repository: "nginx"
      tag: "latest"
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 64Mi
        cpu: 50m
