# Default values for tenant-chart.
tenantId: "example-tenant"

# Global settings for node selection and tolerations
global:
  nodeSelector:
    node-type: applications
  tolerations:
    - key: "applications"
      operator: "Exists"
      effect: "NoSchedule"

# Application configurations
apps:
  wordpress:
    enabled: true
    replicaCount: 1
    image:
      repository: "wordpress"  # Official WordPress image
      tag: "latest"            # Use the latest stable version
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 80 # Port for the WordPress service
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    ingress:
      enabled: true
      className: "nginx"
      pathType: Prefix
      tls: []
    affinity: {}
