# Default values for tenant-chart.
tenantId: "example-tenant"  # This will be dynamically replaced for each tenant
host: "test1.faralpha.com"  # Single static domain

# Global settings for node selection and tolerations
global:
  storageClassName: linode-block-storage-retain
  namespace: default

# Application configurations
apps:
  wordpress:
    enabled: true
    replicaCount: 1
    image:
      repository: "wordpress"
      tag: "latest"
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 80
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      pathType: Prefix
      tls: []
    storageClassName: linode-block-storage-retain
    storageSize: "1Gi"

  mysql:
    enabled: true
    ingress:
      enabled: false
    useStatefulSet: true
    replicaCount: 1
    image:
      repository: "mysql"
      tag: "8.0"
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 3306
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    storageClassName: linode-block-storage-retain
    storageSize: "5Gi"
