# Default values for tenant-chart.
tenantId: "example-tenant"

# Global settings for node selection and tolerations
global:
  nodeSelector:
    node-type: applications
  tolerations:
    - key: "applications"
      operator: "Exists"
      effect: "NoSchedule"
  namespace: default # Added a global namespace for consistency

# Application configurations
apps:
  wordpress:
    enabled: true
    replicaCount: 1
    image:
      repository: "wordpress"  # Official WordPress image
      tag: "latest"            # Use the latest stable version
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 80 # Port for the WordPress service
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    ingress:
      enabled: true
      className: "nginx"
      annotations: # Added annotations for better control
        nginx.ingress.kubernetes.io/rewrite-target: /
      pathType: Prefix
      tls: []
    affinity: {}
    storageSize: "1Gi" # Add this field for PVC

  mysql:
    enabled: true
    useStatefulSet: true
    replicaCount: 1
    image:
      repository: "mysql"       # Official MySQL image
      tag: "8.0"                # Specify a stable MySQL version
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
    service:
      type: ClusterIP
      port: 3306 # Port for the MySQL service
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    ingress:
      enabled: false
    affinity: {}
    storageSize: "5Gi" # Added storage size for database persistence
  #Just a place holder for future apps
  producer:
    enabled: false 
    service:
      type: ClusterIP
      port: 8080 
    ingress:
      enabled: false 
    image:
      tag: "0.1" 

  consumer:
    enabled: false 
    service:
      type: ClusterIP
      port: 9090 
    ingress:
      enabled: false 
    image:
      tag: "0.1" 