apiVersion: v1
kind: Namespace
metadata:
  name: dummy

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-dummy
  namespace: dummy
  spec:
    releaseName: wordpress-dummy
    chart:
      spec:
        chart: ./charts/wordpress-mysql
        sourceRef:
          kind: GitRepository
          name: my-git-repo
          namespace: flux-system
    values:
      wordpressUsername: dummy-user
      wordpressPassword: dummy-password
      wordpressEmail: dummy@example.com
