apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-dummy
  namespace: dummy
spec:
  interval: 1m  # Add this line
  releaseName: wordpress-dummy
  chart:
    spec:
      chart: ./charts/wordpress-mysql
      sourceRef:
        kind: GitRepository
        name: wordpress-repo
        namespace: flux-system
  values:
    wordpressUsername: dummy-user
    wordpressPassword: dummy-password
    wordpressEmail: dummy@example.com
