apiVersion: v1
kind: Namespace
metadata:
  name: tenant1

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-tenant1
  namespace: tenant1
  spec:
    releaseName: wordpress-tenant1
    chart:
      spec:
        chart: ./charts/wordpress-mysql
        sourceRef:
          kind: GitRepository
          name: my-git-repo
          namespace: flux-system
    values:
      wordpressUsername: tenant1-user
      wordpressPassword: tenant1-password
      wordpressEmail: tenant1@example.com
