apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress-tenant1
  namespace: tenant1
spec:
  interval: 1m  # Add this line
  releaseName: wordpress-tenant1
  chart:
    spec:
      chart: ./charts/wordpress-mysql
      sourceRef:
        kind: GitRepository
        name: wordpress-repo
        namespace: flux-system
  values:
    wordpressUsername: tenant1-user
    wordpressPassword: tenant1-password
    wordpressEmail: tenant1@example.com
