apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tenant-b6ad46.yaml
  - dummy-configmap.yaml
  - tenant-19bc5f.yaml
  - tenant-6e4dcb.yaml
  - tenant-949a37.yaml

  - tenant-f3514e.yaml
