apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dummy-configmap.yaml
  - tenant-ec3bc.yaml
  - tenant-33f34.yaml
  - tenant-7dae4.yaml
  - tenant-71507.yaml
  - tenant-df4d8.yaml
  - tenant-c8ea8.yaml
  - tenant-22230.yaml
  - tenant-8375d.yaml