apiVersion: v1
kind: Namespace
metadata:
  name: tenant-ab2318
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-ab2318-premium
  namespace: flux-system
spec:
  releaseName: tenant-ab2318-premium
  targetNamespace: tenant-ab2318
  storageNamespace: tenant-ab2318
  interval: 1m0s
  chart:
    spec:
      chart: ./helm-charts/helm-tenant-chart
      version: "1.9.x"
      sourceRef:
        kind: GitRepository
        name: helm-tenant-chart
  values:
    tenantId: tenant-ab2318
    host: test1@faralpha.com
    apps: {}
    