apiVersion: v1
kind: Namespace
metadata:
  name: tenant-d5633
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-d5633-premium
  namespace: flux-system
spec:
  releaseName: tenant-d5633-premium
  targetNamespace: tenant-d5633
  storageNamespace: tenant-d5633
  interval: 1m0s
  chart:
    spec:
      chart: ./helm-charts/helm-tenant-chart
      version: "1.9.x"
      sourceRef:
        kind: GitRepository
        name: helm-tenant-chart
  values:
    tenantId: tenant-d5633
    host: test18.faralpha.com
    apps: {}
    