apiVersion: v1
kind: Namespace
metadata:
  name: tenant-90999
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-90999-premium
  namespace: flux-system
spec:
  releaseName: tenant-90999-premium
  targetNamespace: tenant-90999
  storageNamespace: tenant-90999
  interval: 1m0s
  chart:
    spec:
      chart: ./helm-charts/helm-tenant-chart
      version: "1.9.x"
      sourceRef:
        kind: GitRepository
        name: helm-tenant-chart
  values:
    tenantId: tenant-90999
    host: test10.faralpha.com
    apps: {}
    