apiVersion: v1
kind: Namespace
metadata:
  name: tenant-4fcd52
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-4fcd52-premium
  namespace: flux-system
spec:
  releaseName: tenant-4fcd52-premium
  targetNamespace: tenant-4fcd52
  storageNamespace: tenant-4fcd52
  interval: 1m0s
  chart:
    spec:
      chart: ./helm-charts/helm-tenant-chart
      version: "1.9.x"
      sourceRef:
        kind: GitRepository
        name: helm-tenant-chart
  values:
    tenantId: tenant-4fcd52
    host: test1@faralpha.com
    apps: {}
    