image:
  repository: wordpress
  tag: latest

wordpressUsername: admin
wordpressPassword: password
wordpressEmail: admin@example.com
wordpressBlogName: "My Blog"

mariadb:
  enabled: true
  db:
    user: wordpress
    password: wordpress-password
    name: wordpress

service:
  type: ClusterIP
  port: 80

mysql:
  persistence:
    enabled: true
    size: 8Gi                    # Size of the PersistentVolume
    storageClass: standard        # Specify the storage class (or leave it blank for default)
